/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2022-03-06-b9973b7"
#endif /* AVUTIL_FFVERSION_H */
